version: "3.7"

services:
  laravel:
    build:
      dockerfile: Dockerfile
    container_name: assignment01-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    volumes:
      - ./src:/var/www/html
    ports:
      - "1234:80"
    command: >
      sh -c "
        composer install &&
        chmod -R 775 storage bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        php artisan migrate &&
        apache2-foreground
      "
  mysql:
    image: mysql:8
    container_name: assignment01-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
