version: "3.7"

services:
  laravel:
    build:
      dockerfile: Dockerfile
    container_name: assignment01-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    volumes:
      - ./src:/var/www/html
    ports:
      - "1234:1234"
    command: >
      sh -c "
        composer install &&
        chmod -R 775 storage bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        php artisan migrate &&
        php-fpm
      "

  frontend:
    image: node:20
    container_name: yomuhoudai-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        pnpm install &&
        pnpm dev --host
      "

  mysql:
    image: mysql:8
    container_name: assignment01-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
