version: "3.7"

services:
  laravel:
    image: yaraku/assignment:${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"

  frontend:
    image: node:20
    container_name: yomuhoudai-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        pnpm install &&
        pnpm dev --host
      "

  mysql:
    image: mysql:8
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
