version: "3.7"

services:
  laravel:
    build:
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: "false" # you can make this true for dev mode
      APP_ENV: production # set it to local in dev mode
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
      L5_SWAGGER_CONST_HOST: laravel.yomuhoudai.club
      L5_SWAGGER_USE_ABSOLUTE_PATH: false
    volumes:
      - ./src:/var/www/html
    ports:
      - "1234:1234"

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
