version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    volumes:
      - ./src:/var/www/html
    ports:
      - "1234:1234"
    command: >
      sh -c "
        composer install &&
        chmod -R 775 storage bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        apache2-foreground
      "

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
