<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        DB::table('books')->insert([
            [
                'title' => 'Crime and Punishment',
                'author' => 'Fyodor Dostoevsky',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8225266-L.jpg',
                'description' => 'Raskolnikov, a student, commits a murder and faces a battle of guilt and redemption.',
                'categories' => json_encode(['Classic', 'Psychological']),
                'pageCount' => 671,
                'publishedDate' => '1866-01-01',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Brothers Karamazov',
                'author' => 'Fyodor Dostoevsky',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8281990-L.jpg',
                'description' => 'A philosophical novel exploring faith, doubt, free will, and morality through the lives of the Karamazov brothers.',
                'categories' => json_encode(['Philosophy', 'Classic']),
                'pageCount' => 796,
                'publishedDate' => '1880-01-01',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Norwegian Wood',
                'author' => 'Haruki Murakami',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/10419969-L.jpg',
                'description' => 'A nostalgic story of loss and sexuality in 1960s Tokyo.',
                'categories' => json_encode(['Fiction', 'Romance']),
                'pageCount' => 386,
                'publishedDate' => '1987-09-04',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Kafka on the Shore',
                'author' => 'Haruki Murakami',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/240726-L.jpg',
                'description' => 'A metaphysical mind-bender blending fantasy, dreams, and classical music.',
                'categories' => json_encode(['Fantasy', 'Magical Realism']),
                'pageCount' => 505,
                'publishedDate' => '2002-09-12',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Beloved',
                'author' => 'Toni Morrison',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/9251983-L.jpg',
                'description' => 'Set after the American Civil War, a former slave is haunted by her past and the ghost of her dead daughter.',
                'categories' => json_encode(['Historical Fiction']),
                'pageCount' => 324,
                'publishedDate' => '1987-09-01',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'One Hundred Years of Solitude',
                'author' => 'Gabriel García Márquez',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
                'description' => 'A multi-generational story of the Buendía family in the town of Macondo.',
                'categories' => json_encode(['Magical Realism']),
                'pageCount' => 417,
                'publishedDate' => '1967-05-30',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Road',
                'author' => 'Cormac McCarthy',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
                'description' => 'A bleak post-apocalyptic journey of a father and his son across a burned America.',
                'categories' => json_encode(['Post-apocalyptic', 'Drama']),
                'pageCount' => 287,
                'publishedDate' => '2006-09-26',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Name of the Wind',
                'author' => 'Patrick Rothfuss',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/6991532-L.jpg',
                'description' => 'The tale of a magically gifted young man who grows to be the most notorious wizard his world has ever seen.',
                'categories' => json_encode(['Fantasy']),
                'pageCount' => 662,
                'publishedDate' => '2007-03-27',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Lies of Locke Lamora',
                'author' => 'Scott Lynch',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8158342-L.jpg',
                'description' => 'A clever thief and con artist navigates the criminal underworld of Camorr.',
                'categories' => json_encode(['Fantasy', 'Crime']),
                'pageCount' => 722,
                'publishedDate' => '2006-06-27',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Do Androids Dream of Electric Sheep?',
                'author' => 'Philip K. Dick',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8672265-L.jpg',
                'description' => 'Rick Deckard hunts rogue androids in a post-apocalyptic Earth. Basis for Blade Runner.',
                'categories' => json_encode(['Science Fiction']),
                'pageCount' => 210,
                'publishedDate' => '1968-03-01',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Left Hand of Darkness',
                'author' => 'Ursula K. Le Guin',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8231991-L.jpg',
                'description' => 'A diplomat navigates a world of ambisexual people and explores themes of gender and identity.',
                'categories' => json_encode(['Science Fiction']),
                'pageCount' => 304,
                'publishedDate' => '1969-01-01',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Cloud Atlas',
                'author' => 'David Mitchell',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/7397481-L.jpg',
                'description' => 'Six nested stories spanning centuries, exploring the interconnectedness of actions.',
                'categories' => json_encode(['Literary Fiction', 'Science Fiction']),
                'pageCount' => 509,
                'publishedDate' => '2004-03-17',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Americanah',
                'author' => 'Chimamanda Ngozi Adichie',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/8224153-L.jpg',
                'description' => 'A Nigerian woman struggles with identity, love, and race while living abroad.',
                'categories' => json_encode(['Contemporary']),
                'pageCount' => 477,
                'publishedDate' => '2013-05-14',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'A Fine Balance',
                'author' => 'Rohinton Mistry',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/7221861-L.jpg',
                'description' => 'Four characters’ lives intertwine in 1970s India under political upheaval.',
                'categories' => json_encode(['Historical Fiction']),
                'pageCount' => 603,
                'publishedDate' => '1995-10-23',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'The Wind-Up Bird Chronicle',
                'author' => 'Haruki Murakami',
                'currentPage' => 0,
                'cover' => 'https://covers.openlibrary.org/b/id/10518217-L.jpg',
                'description' => 'A Tokyo man searches for his missing wife and uncovers bizarre, surreal experiences.',
                'categories' => json_encode(['Magical Realism', 'Mystery']),
                'pageCount' => 607,
                'publishedDate' => '1994-04-12',
                'rating' => 0,
                'status' => 'plan-to-read',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
